sudo: false

language: php

services:
  - mysql

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - yoastseo

matrix:
  include:
  - name: Yoast SEO 14.0.2
    php: 7.2
    env: WP_VERSION=4.9 WP_MULTISITE=0 YOAST_VERSION=14.0.2
  - name: Yoast SEO 14.0.3
    php: 7.2
    env: WP_VERSION=4.9 WP_MULTISITE=0 YOAST_VERSION=14.0.3
  - name: Yoast SEO 14.0.4
    php: 7.2
    env: WP_VERSION=4.9 WP_MULTISITE=0 YOAST_VERSION=14.0.4

before_script:
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    fi
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"
  - |
    if [[ "$PHPCS" == "1" ]]; then
      composer global require dealerdirect/phpcodesniffer-composer-installer
      composer global require wp-coding-standards/wpcs
      composer global require automattic/vipwpcs
      composer global require phpcompatibility/phpcompatibility-wp
    else
      bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      bash tests/bin/install-plugins.sh
      composer global require "phpunit/phpunit=5.7.*"
    fi

script:
  - |
    if [[ "$PHPCS" == "1" ]]; then
      phpcs -s --extensions=php,js .
    else
      phpunit
    fi
